### ISSUE TITLE
App: Opiniões Verificadas

### ISSUE THREAD

**Issue by leomp12** [ecomplus/app-opinioes-verificadas#6]
- [x] _WIP_ @talissonf ;
- [x] Ícones para o Market e checkout e descrição em md (@vitorrgg );

**Comment by talissonf** [comment]
https://github.com/ecomplus/app-opinioes-verificadas/releases/tag/v1.0.0

**Comment by leomp12** [comment]
@vitorrgg

**Comment by vitorrgg** [comment]
![opinioesverificadas](https://user-images.githubusercontent.com/35348281/99444950-a714e980-28fb-11eb-8707-d167d45a35f3.png)

**Comment by leomp12** [comment]
@talissonf falta descrição e publicar o app, desembola isso pra nós por favor? Já mudei a _role_ do seu user aqui pra poder mexer nos secrets e adicionar o seu token pro market lá :+1: 

> Pedi a descrição pro @vitorrgg também mas... :neutral_face:

**Comment by talissonf** [comment]
Publicado

**Comment by talissonf** [comment]
@leomp12

**Comment by leomp12** [comment]
Valeu @talissonf !
Lembra de remover esta informação de _BETA_ depois, publicando novamente.

Acho que é importante ter as instruções na descrição do app para ativar o widget no CMS e configurar os plugins no painel do Opiniões Verificadas, talvez a @ThaisChaves ou @matheusgnreis possam ajudar aqui. Tem um tutorial mas é mais acertivo já deixar isso na descrição do aplicativo também.

**Comment by ThaisChaves** [comment]
@matheusgnreis , eu acrescento o restante da configuração, ai, ta! pode deixar!

**Comment by leomp12** [comment]
@talissonf na verdade também faltou descrição curta e categoria do app [aqui](https://github.com/ecomplus/app-opinioes-verificadas/blob/master/ecomplus-market.json)

**Comment by talissonf** [comment]
@leomp12  https://github.com/ecomplus/app-opinioes-verificadas/commit/56fe377a9f7c94e5214a311825c489dba624822d
